linter-settings:
  golangci-lint:
    version: latest
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
