package transport

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/ersinkoc/dfmt/internal/content"
	"github.com/ersinkoc/dfmt/internal/core"
	"github.com/ersinkoc/dfmt/internal/redact"
	"github.com/ersinkoc/dfmt/internal/sandbox"
)

// Handlers implements the business logic for all transport layers.
type Handlers struct {
	index    *core.Index
	journal  core.Journal
	sandbox  sandbox.Sandbox
	project  string
	redactor *redact.Redactor
	store    *content.Store
}

// NewHandlers creates a new Handlers instance.
// Every Event written via Remember and every tool-call log event generated by
// Exec/Read/Fetch is passed through the redactor before the journal sees it.
// Callers that need to inject a custom Redactor (e.g. with extra project
// patterns) can call SetRedactor.
func NewHandlers(index *core.Index, journal core.Journal, sb sandbox.Sandbox) *Handlers {
	return &Handlers{
		index:    index,
		journal:  journal,
		sandbox:  sb,
		redactor: redact.NewRedactor(),
	}
}

// SetRedactor overrides the redactor used by this Handlers instance.
// Pass nil to disable redaction (not recommended outside of tests).
func (h *Handlers) SetRedactor(r *redact.Redactor) { h.redactor = r }

// SetContentStore wires the ephemeral content store so Exec/Read/Fetch can
// stash the full (redacted) raw output for later lookup. The store is
// optional — when nil, Handlers return excerpts only.
func (h *Handlers) SetContentStore(s *content.Store) { h.store = s }

// stashContent writes body as a single-chunk set into the content store and
// returns the chunk set ID. Returns "" when the store is not configured or
// the body is empty. Errors are logged to stderr and swallowed — content
// stashing must never fail a sandbox call.
func (h *Handlers) stashContent(kind, source, intent, body string) string {
	if h.store == nil || body == "" {
		return ""
	}
	setID := string(core.NewULID(time.Now()))
	set := &content.ChunkSet{
		ID:      setID,
		Kind:    kind,
		Source:  source,
		Intent:  intent,
		Created: time.Now(),
	}
	if err := h.store.PutChunkSet(set); err != nil {
		fmt.Fprintf(os.Stderr, "stashContent put set: %v\n", err)
		return ""
	}
	chunk := &content.Chunk{
		ID:       string(core.NewULID(time.Now())),
		ParentID: setID,
		Index:    0,
		Kind:     content.ChunkKindText,
		Body:     body,
		Created:  time.Now(),
	}
	if err := h.store.PutChunk(chunk); err != nil {
		fmt.Fprintf(os.Stderr, "stashContent put chunk: %v\n", err)
		return ""
	}
	return setID
}

// redactString returns s with sensitive data scrubbed, or s unchanged if no
// redactor is configured.
func (h *Handlers) redactString(s string) string {
	if h.redactor == nil || s == "" {
		return s
	}
	return h.redactor.Redact(s)
}

// redactData walks a map[string]any and redacts any string values in place.
// Returns a new map rather than mutating the caller's to keep the API safe
// for concurrent reuse of the original data.
func (h *Handlers) redactData(data map[string]any) map[string]any {
	if h.redactor == nil {
		return data
	}
	return h.redactor.RedactEvent(data)
}

// SetProject sets the project identifier stamped on all events written by this handler.
func (h *Handlers) SetProject(p string) { h.project = p }

// logEvent appends a tool call event to the journal and index.
// Data is redacted before persistence so secrets in tool arguments/output
// don't land in journal.jsonl.
func (h *Handlers) logEvent(ctx context.Context, eventType, summary string, data map[string]any) {
	if h.journal == nil {
		return
	}
	e := core.Event{
		ID:       string(core.NewULID(time.Now())),
		TS:       time.Now(),
		Project:  h.project,
		Type:     core.EventType(eventType),
		Priority: core.PriP4,
		Source:   core.SrcMCP,
		Data:     h.redactData(data),
		Tags:     []string{h.redactString(summary)},
	}
	e.Sig = e.ComputeSig()
	if err := h.journal.Append(ctx, e); err != nil {
		fmt.Fprintf(os.Stderr, "logEvent: journal append: %v\n", err)
	}
	if h.index != nil {
		h.index.Add(e)
	}
}

// RememberParams are the parameters for the Remember method.
type RememberParams struct {
	Type     string         `json:"type"`
	Priority string         `json:"priority"`
	Source   string         `json:"source"`
	Actor    string         `json:"actor,omitempty"`
	Data     map[string]any `json:"data,omitempty"`
	Refs     []string       `json:"refs,omitempty"`
	Tags     []string       `json:"tags,omitempty"`
	// Direct token fields for MCP tools
	InputTokens  int    `json:"input_tokens,omitempty"`
	OutputTokens int    `json:"output_tokens,omitempty"`
	CachedTokens int    `json:"cached_tokens,omitempty"`
	Model        string `json:"model,omitempty"`
	Message      string `json:"message,omitempty"`
}

// RememberResponse is the response for the Remember method.
type RememberResponse struct {
	ID string `json:"id"`
	TS string `json:"ts"`
}

// Remember adds an event to the journal and index.
func (h *Handlers) Remember(ctx context.Context, params RememberParams) (*RememberResponse, error) {
	// Handle direct token fields - add to Data map
	data := params.Data
	if params.InputTokens > 0 || params.OutputTokens > 0 || params.CachedTokens > 0 || params.Model != "" {
		if data == nil {
			data = make(map[string]any)
		}
		if params.InputTokens > 0 {
			data[core.KeyInputTokens] = params.InputTokens
		}
		if params.OutputTokens > 0 {
			data[core.KeyOutputTokens] = params.OutputTokens
		}
		if params.CachedTokens > 0 {
			data[core.KeyCachedTokens] = params.CachedTokens
		}
		if params.Model != "" {
			data[core.KeyModel] = params.Model
		}
	}

	// Redact sensitive strings before the event is persisted or indexed.
	redactedTags := params.Tags
	if h.redactor != nil && len(redactedTags) > 0 {
		redactedTags = make([]string, len(params.Tags))
		for i, t := range params.Tags {
			redactedTags[i] = h.redactString(t)
		}
	}

	// Create event
	e := core.Event{
		ID:       string(core.NewULID(time.Now())),
		TS:       time.Now(),
		Project:  h.project,
		Type:     core.EventType(params.Type),
		Priority: core.Priority(params.Priority),
		Source:   core.Source(params.Source),
		Actor:    params.Actor,
		Data:     h.redactData(data),
		Refs:     params.Refs,
		Tags:     redactedTags,
	}
	e.Sig = e.ComputeSig()

	// Append to journal
	if err := h.journal.Append(ctx, e); err != nil {
		return nil, fmt.Errorf("journal append: %w", err)
	}

	// Add to index
	h.index.Add(e)

	return &RememberResponse{
		ID: e.ID,
		TS: e.TS.Format(time.RFC3339Nano),
	}, nil
}

// SearchParams are the parameters for the Search method.
type SearchParams struct {
	Query string `json:"query"`
	Limit int    `json:"limit,omitempty"`
	Layer string `json:"layer,omitempty"` // "bm25", "trigram", "fuzzy"
}

// SearchResponse is the response for the Search method.
type SearchResponse struct {
	Results []SearchHit `json:"results"`
	Layer   string      `json:"layer"`
}

// SearchHit represents a single search result.
type SearchHit struct {
	ID     string  `json:"id"`
	Score  float64 `json:"score"`
	Layer  int     `json:"layer"`
	Type   string  `json:"type,omitempty"`
	Source string  `json:"source,omitempty"`
}

// Search queries the index.
func (h *Handlers) Search(ctx context.Context, params SearchParams) (*SearchResponse, error) {
	if params.Limit == 0 {
		params.Limit = 10
	}

	if h.index == nil {
		return &SearchResponse{Results: nil, Layer: params.Layer}, nil
	}

	var hits []core.ScoredHit

	switch params.Layer {
	case "trigram":
		// Trigram search would go here
		hits = nil
	case "fuzzy":
		// Fuzzy search would go here
		hits = nil
	default:
		// Default to BM25
		hits = h.index.SearchBM25(params.Query, params.Limit)
	}

	results := make([]SearchHit, len(hits))
	for i, hit := range hits {
		results[i] = SearchHit{
			ID:    hit.ID,
			Score: hit.Score,
			Layer: hit.Layer,
		}
	}

	return &SearchResponse{
		Results: results,
		Layer:   params.Layer,
	}, nil
}

// RecallParams are the parameters for the Recall method.
type RecallParams struct {
	Budget int    `json:"budget,omitempty"`
	Format string `json:"format,omitempty"`
}

// RecallResponse is the response for the Recall method.
type RecallResponse struct {
	Snapshot string `json:"snapshot"`
	Format   string `json:"format"`
}

// Recall builds a session snapshot with tier-ordered greedy fill.
func (h *Handlers) Recall(ctx context.Context, params RecallParams) (*RecallResponse, error) {
	budget := params.Budget
	if budget == 0 {
		budget = 4096
	}
	format := params.Format
	if format == "" {
		format = "md"
	}

	// Get all events from journal
	var events []core.Event
	stream, err := h.journal.Stream(ctx, "")
	if err != nil {
		return nil, fmt.Errorf("stream journal: %w", err)
	}
	for e := range stream {
		events = append(events, e)
	}

	// Classify and sort by priority (P1 first), then by timestamp descending
	classifier := core.NewClassifier()
	sorted := make([]core.Event, len(events))
	copy(sorted, events)
	sort.Slice(sorted, func(i, j int) bool {
		pi := classifier.Classify(sorted[i])
		pj := classifier.Classify(sorted[j])
		if pi != pj {
			return pi < pj // P1 < P2 < P3 < P4
		}
		return sorted[i].TS.After(sorted[j].TS)
	})

	// Greedy fill with budget
	var used int
	var lines []string
	lines = append(lines, "# Session Snapshot\n")

	for _, e := range sorted {
		// Estimate size: event as markdown line
		prefix := fmt.Sprintf("- [%s] %s", e.Priority, e.Type)
		var dataStr string
		if e.Data != nil {
			dataStr = formatEventData(e.Data)
		}
		lineSize := len(prefix) + len(dataStr) + len(e.Tags)*10 + 50 // rough estimate

		if used+lineSize > budget {
			continue
		}

		ts := e.TS.Format("15:04:05")
		actor := ""
		if e.Actor != "" {
			actor = fmt.Sprintf(" @%s", e.Actor)
		}
		tags := ""
		if len(e.Tags) > 0 {
			tags = fmt.Sprintf(" #%s", strings.Join(e.Tags, " #"))
		}
		line := fmt.Sprintf("- [%s] %s%s%s%s", e.Priority, ts, actor, tags, dataStr)
		lines = append(lines, line)
		used += lineSize
	}

	if len(lines) == 1 {
		lines = append(lines, "_No events in session_")
	}

	return &RecallResponse{
		Snapshot: strings.Join(lines, "\n"),
		Format:   format,
	}, nil
}

// StatsParams are the parameters for the Stats method.
type StatsParams struct{}

// StatsResponse is the response for the Stats method.
type StatsResponse struct {
	EventsTotal      int            `json:"events_total"`
	EventsByType     map[string]int `json:"events_by_type"`
	EventsByPriority map[string]int `json:"events_by_priority"`
	SessionStart     string         `json:"session_start"`
	SessionEnd       string         `json:"session_end"`
	// Token metrics
	TotalInputTokens  int     `json:"total_input_tokens"`
	TotalOutputTokens int     `json:"total_output_tokens"`
	TotalCachedTokens int     `json:"total_cached_tokens"`
	TokenSavings      int     `json:"token_savings"`
	CacheHitRate      float64 `json:"cache_hit_rate"`
}

// Stats returns aggregated statistics from the journal.
// Aggregates as events stream in — O(|event-types| + |priorities|) memory,
// not O(|journal|). The previous implementation buffered every event into a
// slice, which grew unbounded on long-running projects.
func (h *Handlers) Stats(ctx context.Context, params StatsParams) (*StatsResponse, error) {
	stream, err := h.journal.Stream(ctx, "")
	if err != nil {
		return nil, fmt.Errorf("stream journal: %w", err)
	}

	resp := &StatsResponse{
		EventsByType:     make(map[string]int),
		EventsByPriority: make(map[string]int),
	}

	classifier := core.NewClassifier()
	var earliest, latest time.Time
	var totalInput, totalOutput, totalCached int
	total := 0

	for e := range stream {
		total++
		resp.EventsByType[string(e.Type)]++
		resp.EventsByPriority[string(classifier.Classify(e))]++

		if inputTokens, ok := getInt(e.Data, core.KeyInputTokens); ok {
			totalInput += inputTokens
		}
		if outputTokens, ok := getInt(e.Data, core.KeyOutputTokens); ok {
			totalOutput += outputTokens
		}
		if cachedTokens, ok := getInt(e.Data, core.KeyCachedTokens); ok {
			totalCached += cachedTokens
		}

		if earliest.IsZero() || e.TS.Before(earliest) {
			earliest = e.TS
		}
		if latest.IsZero() || e.TS.After(latest) {
			latest = e.TS
		}
	}

	resp.EventsTotal = total
	resp.TotalInputTokens = totalInput
	resp.TotalOutputTokens = totalOutput
	resp.TotalCachedTokens = totalCached
	resp.TokenSavings = totalCached
	if totalInput > 0 {
		resp.CacheHitRate = float64(totalCached) / float64(totalInput) * 100
	}

	if !earliest.IsZero() {
		resp.SessionStart = earliest.Format(time.RFC3339)
	}
	if !latest.IsZero() {
		resp.SessionEnd = latest.Format(time.RFC3339)
	}

	return resp, nil
}

// formatEventData formats event data for display, highlighting token fields.
func formatEventData(data map[string]any) string {
	if data == nil {
		return ""
	}
	// Check for token fields
	inputTokens, _ := getInt(data, core.KeyInputTokens)
	outputTokens, _ := getInt(data, core.KeyOutputTokens)
	cachedTokens, _ := getInt(data, core.KeyCachedTokens)
	model, hasModel := data[core.KeyModel]

	if inputTokens > 0 || outputTokens > 0 || cachedTokens > 0 {
		var parts []string
		if inputTokens > 0 {
			parts = append(parts, fmt.Sprintf("in:%d", inputTokens))
		}
		if outputTokens > 0 {
			parts = append(parts, fmt.Sprintf("out:%d", outputTokens))
		}
		if cachedTokens > 0 {
			parts = append(parts, fmt.Sprintf("cached:%d", cachedTokens))
		}
		if hasModel && model != nil {
			parts = append(parts, fmt.Sprintf("@%v", model))
		}
		return " " + strings.Join(parts, " ")
	}

	// Default: use first few keys as summary
	var keys []string
	for k := range data {
		keys = append(keys, k)
	}
	if len(keys) == 0 {
		return ""
	}
	// Show up to 3 key=value pairs
	summary := ""
	for i := 0; i < len(keys) && i < 3; i++ {
		if summary != "" {
			summary += " "
		}
		summary += fmt.Sprintf("%s:%v", keys[i], data[keys[i]])
	}
	if len(keys) > 3 {
		summary += " ..."
	}
	return " " + summary
}

// getInt extracts an integer from a map[string]any.
func getInt(data map[string]any, key string) (int, bool) {
	if data == nil {
		return 0, false
	}
	val, ok := data[key]
	if !ok {
		return 0, false
	}
	switch v := val.(type) {
	case int:
		return v, true
	case int64:
		return int(v), true
	case float64:
		return int(v), true
	default:
		return 0, false
	}
}

// StreamParams are the parameters for the Stream method.
type StreamParams struct {
	From string `json:"from,omitempty"`
}

// Stream streams events from the journal.
func (h *Handlers) Stream(ctx context.Context, params StreamParams) (<-chan core.Event, error) {
	return h.journal.Stream(ctx, params.From)
}

// ── Sandbox wrappers ───────────────────────────────────────────────

// ExecParams are the parameters for sandbox execution.
type ExecParams struct {
	Code    string            `json:"code"`
	Lang    string            `json:"lang,omitempty"`
	Intent  string            `json:"intent,omitempty"`
	Timeout int               `json:"timeout,omitempty"` // seconds
	Return  string            `json:"return,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
}

// ExecResponse is the response from sandbox execution.
type ExecResponse struct {
	Exit       int                    `json:"exit"`
	Stdout     string                 `json:"stdout,omitempty"`
	Stderr     string                 `json:"stderr,omitempty"`
	Summary    string                 `json:"summary,omitempty"`
	Matches    []sandbox.ContentMatch `json:"matches,omitempty"`
	Vocabulary []string               `json:"vocabulary,omitempty"`
	DurationMs int                    `json:"duration_ms"`
	TimedOut   bool                   `json:"timed_out"`
	ContentID  string                 `json:"content_id,omitempty"`
}

// Exec executes code via the sandbox.
func (h *Handlers) Exec(ctx context.Context, params ExecParams) (*ExecResponse, error) {
	var timeout time.Duration
	if params.Timeout > 0 {
		timeout = time.Duration(params.Timeout) * time.Second
	} else {
		timeout = sandbox.DefaultExecTimeout
	}

	req := sandbox.ExecReq{
		Code:    params.Code,
		Lang:    params.Lang,
		Intent:  params.Intent,
		Timeout: timeout,
		Return:  params.Return,
		Env:     params.Env,
	}

	resp, err := h.sandbox.Exec(ctx, req)
	if err != nil {
		return nil, err
	}

	// Log the invocation. Code goes in redacted because secrets leak through
	// command lines far more often than through stdout.
	h.logEvent(ctx, "tool.exec", params.Intent, map[string]any{
		"code":     params.Code,
		"lang":     params.Lang,
		"exit":     resp.Exit,
		"duration": resp.DurationMs,
	})

	stdout := h.redactString(resp.Stdout)
	stderr := h.redactString(resp.Stderr)
	contentID := h.stashContent("exec-stdout", "sandbox.exec", params.Intent, stdout+stderr)

	return &ExecResponse{
		Exit:       resp.Exit,
		Stdout:     stdout,
		Stderr:     stderr,
		Summary:    h.redactString(resp.Summary),
		Matches:    h.redactMatches(resp.Matches),
		Vocabulary: resp.Vocabulary,
		DurationMs: resp.DurationMs,
		TimedOut:   resp.TimedOut,
		ContentID:  contentID,
	}, nil
}

// redactMatches returns a new slice with Text fields redacted.
func (h *Handlers) redactMatches(in []sandbox.ContentMatch) []sandbox.ContentMatch {
	if h.redactor == nil || len(in) == 0 {
		return in
	}
	out := make([]sandbox.ContentMatch, len(in))
	for i, m := range in {
		m.Text = h.redactString(m.Text)
		out[i] = m
	}
	return out
}

// ReadParams are the parameters for sandbox file reading.
type ReadParams struct {
	Path   string `json:"path"`
	Intent string `json:"intent,omitempty"`
	Offset int64  `json:"offset,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Return string `json:"return,omitempty"`
}

// ReadResponse is the response from sandbox file reading.
type ReadResponse struct {
	Content   string                 `json:"content,omitempty"`
	Summary   string                 `json:"summary,omitempty"`
	Matches   []sandbox.ContentMatch `json:"matches,omitempty"`
	Size      int64                  `json:"size"`
	ReadBytes int64                  `json:"read_bytes"`
	ContentID string                 `json:"content_id,omitempty"`
}

// Read reads a file via the sandbox.
func (h *Handlers) Read(ctx context.Context, params ReadParams) (*ReadResponse, error) {
	req := sandbox.ReadReq{
		Path:   params.Path,
		Intent: params.Intent,
		Offset: params.Offset,
		Limit:  params.Limit,
		Return: params.Return,
	}

	resp, err := h.sandbox.Read(ctx, req)
	if err != nil {
		return nil, err
	}

	h.logEvent(ctx, "tool.read", params.Intent, map[string]any{
		"path":       params.Path,
		"read_bytes": resp.ReadBytes,
		"size":       resp.Size,
	})

	redContent := h.redactString(resp.Content)
	contentID := h.stashContent("file-read", params.Path, params.Intent, redContent)

	return &ReadResponse{
		Content:   redContent,
		Summary:   h.redactString(resp.Summary),
		Matches:   h.redactMatches(resp.Matches),
		Size:      resp.Size,
		ReadBytes: resp.ReadBytes,
		ContentID: contentID,
	}, nil
}

// FetchParams are the parameters for sandbox HTTP fetching.
type FetchParams struct {
	URL     string            `json:"url"`
	Intent  string            `json:"intent,omitempty"`
	Method  string            `json:"method,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
	Return  string            `json:"return,omitempty"`
	Timeout int               `json:"timeout,omitempty"` // seconds
}

// FetchResponse is the response from sandbox HTTP fetching.
type FetchResponse struct {
	Status     int                    `json:"status"`
	Headers    map[string]string      `json:"headers,omitempty"`
	Body       string                 `json:"body,omitempty"`
	Summary    string                 `json:"summary,omitempty"`
	Matches    []sandbox.ContentMatch `json:"matches,omitempty"`
	Vocabulary []string               `json:"vocabulary,omitempty"`
	TimedOut   bool                   `json:"timed_out"`
	ContentID  string                 `json:"content_id,omitempty"`
}

// Fetch fetches a URL via the sandbox.
func (h *Handlers) Fetch(ctx context.Context, params FetchParams) (*FetchResponse, error) {
	var timeout time.Duration
	if params.Timeout > 0 {
		timeout = time.Duration(params.Timeout) * time.Second
	} else {
		timeout = 30 * time.Second
	}

	req := sandbox.FetchReq{
		URL:     params.URL,
		Intent:  params.Intent,
		Method:  params.Method,
		Headers: params.Headers,
		Body:    params.Body,
		Return:  params.Return,
		Timeout: timeout,
	}

	resp, err := h.sandbox.Fetch(ctx, req)
	if err != nil {
		return nil, err
	}

	h.logEvent(ctx, "tool.fetch", params.Intent, map[string]any{
		"url":    params.URL,
		"status": resp.Status,
	})

	redBody := h.redactString(resp.Body)
	contentID := h.stashContent("fetch", params.URL, params.Intent, redBody)

	return &FetchResponse{
		Status:     resp.Status,
		Headers:    resp.Headers,
		Body:       redBody,
		Summary:    h.redactString(resp.Summary),
		Matches:    h.redactMatches(resp.Matches),
		Vocabulary: resp.Vocabulary,
		TimedOut:   resp.TimedOut,
		ContentID:  contentID,
	}, nil
}
